echo '=== DIAGNÓSTICO DE CORE.PY ==='
echo ''
echo '1. NOMBRE DEL ARCHIVO:'
ls aee\core.py | Select-Object Name, Length
echo ''
echo '2. PRIMERAS 20 LÍNEAS:'
Get-Content aee\core.py -TotalCount 20
echo ''
echo '3. BUSCANDO CLASES:'
Get-Content aee\core.py | Select-String '^class '
echo ''
echo '4. BUSCANDO certify_file:'
Get-Content aee\core.py | Select-String 'def certify_file'
echo ''
echo '5. BUSCANDO initialize:'
Get-Content aee\core.py | Select-String 'def initialize'
